import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    mainContainer:{
        flex:1,
        flexDirection:'column',
        backgroundColor:'#F7F7FA',
        justifyContent:'flex-end'
    },
    topView:{
        alignItems:'center',
        backgroundColor:'#FF6464',
        borderBottomLeftRadius:10,
        borderBottomRightRadius:10
    },
    topText:{
        fontSize:25,
        color:'white',
        padding:5
    },
    btn_view:{
        justifyContent:'center',
        backgroundColor:'black',
        borderRadius:60,
        elevation:6,
        width:50,
        margin:20,
        height:50,
    },
    text_inside_btn:{
        color:'white',
        alignSelf:'center',
        fontSize:30
    },
    dataView:{
        padding:2
    },
    text:{
        fontSize:15,
        fontWeight:'bold',
        color:'#252525',
        margin:8
    },
    flatListView:{
        flexDirection:'row',
        alignSelf:'center',
        marginHorizontal:20,
        width:'95%',
        margin:10,
        elevation:6,
        justifyContent:'space-between',
        borderColor:'white',
        backgroundColor:"#f7f7fa",
        borderRadius:15,
        borderWidth:2,
    },
    eyeImage:{
        alignSelf:'center',
        marginRight:20,
        tintColor:'#FF6464'
    },
    buttonView:{
        alignSelf:'flex-end',
        position:'absolute'
    }

})

export default styles;